### PR TITLE
Move test script and test manifest into schemas repo.

### PR DESCRIPTION
**Pull request by gtback**

### CODE REVIEW

**Comment by bschmoker** [comment]
:+1:  though I would hold off merging until branch #271 is resolved

**Comment by gtback** [comment]
Agreed. There are some other changes I want to make to this before merging. I mostly made this branch and PR to kick off a Travis build, which passed. 

I'll assign myself so no one else is tempted to merge this before it's ready.

**Comment by bschmoker** [comment]
@gtback :cool: 
For ref, you can also [kick-off a manual rebuild in Travis](http://stackoverflow.com/a/17624403)

**Comment by gtback** [comment]
Thanks, @bschmoker . I do use that feature a lot when there are PyPI shenanigans.

In this case I needed to test a new commit (6c01095573c54f59a4d973a9655c7505c86dc136) consisting of just moving the test runner script and manifest between repos, before I started modifying the test runner script.

**Pull request merged**
