### PR TITLE
Set up travis

### PR DESCRIPTION
**Pull request by bschmoker**
@rpiazza - This adds a config and test case generation

### CODE REVIEW

**Comment by gtback** [comment]
I'm not sure if we want to keep all of the test data in the repository?

**Comment by bschmoker** [comment]
@gtback Hmm, we could have a different repo like `test-cases` and pull it as part of the build?
cc: @rpiazza

**Comment by gtback** [comment]
I'm fine having some "negative test cases" in the repo (and even the corresponding positive cases), but having >4700 XML files might be a bit much.

**Comment by bschmoker** [comment]
It's sorta a tradeoff between having local files and a static config  (listing each file and its disposition) or remote files and a dynamic config (which seems a bit bananas)

**Comment by rpiazza** [comment]
@gtback , @bschmoker Can you guys discuss why having many test cases is an issue?  Is it a github thing, travis thing or something else??

**Comment by bschmoker** [comment]
@rpiazza There's not (IMO) technical restrictions, more of repo cleanliness 
Would you agree @gtback ?

**Comment by gtback** [comment]
Repository size/cleanliness, plus it becomes an issue of what we're actually testing by including them. If there were a bug in veris-to-stix, it would likely result in many of these files failing at the same time. I would rather keep isolated test cases that test specific features, and perhaps a few? (few dozen?) general "real world" STIX files.

**Comment by bschmoker** [comment]
@gtback @rpiazza - check out this commit :smile_cat:

**Comment by rpiazza** [comment]
Looks good to me.  @gtback would like to do the pull?

**Comment by gtback** [comment]
In the interest of keeping the git repository small, I rebased this branch and squashed the two commits that added and then removed a ton of files. I'm going to close this PR, but open and merge another one.

**Pull request closed without merging**
