### PR TITLE
Remove id uniqueness constraint

### LINKED ISSUE #236: Remove xs:unique contraint on IDs due to issues with timestamps
Right now it will mark different versions of the same `@id` as invalid.

### PR DESCRIPTION
**Pull request by bworrell**
This PR closes #236. Removed `<xs:unique>` constraint on STIX schemas.

### CODE REVIEW

**Comment by johnwunder** [comment]
This is kind of a nit (ok 100% a nit) but now that the uniqueness keys are gone you can also remove the namespace alias mappings to schemas that aren't actually used. The only reason they were added was for that key.

Aside from that this looks good.

**Comment by bworrell** [comment]
@johnwunder, wow good catch! I hadn't thought to remove those at all. It should be all set now.

**Comment by johnwunder** [comment]
Ha, the only reason I caught that is because I had to add them in the first place.

**Comment by bworrell** [comment]
@gtback, I think this is all set to merge. Take a look and let me know if anything seems off.

**Comment by gtback** [comment]
Looks good to me. It's going to further break #295, but that should be easy to resolve.

**Pull request merged**
