### PR TITLE
Updated samples

### PR DESCRIPTION
**Pull request by johnwunder**
TODO:

* [x] Add reports to the phishing use case examples
* [x] Add observables to the PIVY and APT1 Appendix G reports
* [ ] Fix titles on APT1 Appendix G reports

### CODE REVIEW

**Comment by bschmoker** [comment]
Suggest running validator against the modified schema for commit 14701f010fa65dc86750524a7fdb55780be9973e . 
AFAIK the edited files aren't included in the default travis build.

Note that #223 was the related issue

**Comment by johnwunder** [comment]
I ran a local validation, should be all set there (though if you want to too a second check never hurts).

**Comment by bschmoker** [comment]
All good

**Comment by sbarnum** [comment]
I reviewed the updated sample content with ONLY an eye toward the addition of Report objects.
If a new Report object was included, I reviewed it for validity and appropriateness.
If a new Report object was not included, I reviewed whether the decision to leave it out was appropriate.
I did NOT review the content for any other changes.

Comments:
- I think the "STIX-CybOX_Phishing_Email_Structured_Output_Example(with_Attached_File_Artifact_Object_Included_by_Reference)" sample and "STIX-CybOX_Phishing_Email_Structured_Output_Example(with_Attached_File_Artifact_object)" sample within the Phishing Use Case Example content should have a Report object added.
- The new Report object in the "fireeye-pivy-report-with-indicators" sample should also include the Observables that are part of that file as they are an inherent part of the report.
- The new Report object in the "Appendix_G_IOCs_Full.xml" and "Appendix_G_IOCs_No_OpenIOC" APT1 samples should also include the Observables that are part of that file as they are an inherent part of the report. There appears to be a separate and larger problem here though in that the Observables specified are not observable patterns but are used as such.
- The three sample versions of the APT1 Appendix G all use different ids for their Report objects but use the same Title. I would suggest slightly modifying the Titles to align with the differential content.

Otherwise, these all look good to me.

**Comment by johnwunder** [comment]
talked to Sean, the phishing stuff is CybOX, not STIX, so won't have the report object

**Pull request merged**
