### PR TITLE
Terminology change for 'fraud detection'

### PR DESCRIPTION
**Pull request by bschmoker**
This changes a few terms and bumps the vocab version for #218

### CODE REVIEW

**Comment by bschmoker** [comment]
@johnwunder - Minor detail: Should the updated DiscoveryMethod vocab be 1.2 or 1.1? 
I intuited the latter based on your above comment, and the notion that it would bump minor versions rather than being in lockstep with the overall schema version

**Comment by bschmoker** [comment]
Note: [The CI build](https://travis-ci.org/STIXProject/schemas/builds/51557947) failed because this branch doesn't have a Travis config - need to merge :sparkle: [this one](https://github.com/STIXProject/schemas/pull/272) first

**Comment by johnwunder** [comment]
I'm pretty sure you got it right and that it should be 1.1 but I think we probably should talk it over. Versioning of vocabs is tricky and we may not have followed our rules correctly in the past.

**Comment by bschmoker** [comment]
will bump to 2.0 based on [our own published guidance](http://stix.mitre.org/language/versioning_policy.html#vocabulary)

**Comment by gtback** [comment]
I'm moving the test script and manifest into the schemas repo. See #278. That makes it easier to say "as of this commit in the schemas repo, here is which test cases should be passing and failing."

**Comment by bschmoker** [comment]
@bworrell I have no idea the meaning of [this error](https://travis-ci.org/STIXProject/schemas/builds/52064000#L307) 

It should be using the local schema with `--schema-dir ./` 
- Is it somehow deciding to use the built-in 'uber-schema' instead?

**Comment by bworrell** [comment]
@bschmoker, I think the issue stems from line 577 in the stix_default_vocabularies.xsd file. The name of the new enum isn't a valid XML type name.

```xml
<xs:simpleType name="stixVocabs:DiscoveryMethodEnum-2.0">
```

Should be.

```xml
<xs:simpleType name="DiscoveryMethodEnum-2.0">
```

**Comment by gtback** [comment]
After the latest build of #278 passes, I'm going to rebase this branch onto that one, so that we can verify the tests run on Travis correctly. I'll open a new pull request once that happens.

**Comment by bschmoker** [comment]
nvmind you got it already @gtback

**Pull request closed without merging**
